### ISSUE TITLE
Support for MongoDB ids

### ISSUE THREAD

**Issue by HaNdTriX** [chiefy/sails-generate-controller-angular#1]
The following lines won't work with mongo ids since they are strings: 

```
$stateParams.id = _.parseInt($stateParams.id);
if (!_.isNaN($stateParams.id)) {
    $scope.<%=id%> = _.find(<%=resourcePluralCap%>, {
        id: $stateParams.id
    });
}
```

https://github.com/chiefy/sails-generate-controller-angular/blob/master/templates/angular/controller.ejs#L36-L41

```
_.parseInt('53b3d2dd47fc86fa30a11d80') -> 53
```

Anyway thanks for the great generator!

**Comment by chiefy** [comment]
:+1: Good spot, will get on that. Thanks for the report!

**Comment by LeonardoGentile** [comment]
I wish I read this before finding it out the hard way :)
